### ISSUE TITLE
Model finetuned for inpainting

### ISSUE THREAD

**Issue by lefreud** [zheng95z/rgbx#2]
Hi,

First of all, thank you for providing a clean and working implementation of RGB<->X !

I was wondering if we could have access to the model finetuned for inpainting (with the additional masked image input)? We would like to use it in our research if possible :)

Thank you!

**Comment by zheng95z** [comment]
Hi @lefreud,

Thanks for your kind words!

For the release of the inpainting model, we're asking around as it needs to go through another round of approvals, thanks for your patience. Feel free to ask me any questions regarding the implementation in the meantime.

**Comment by lefreud** [comment]
Got it, thank you!
