### ISSUE TITLE
Albedo and Irradiance Evaluation

### ISSUE THREAD

**Issue by Guirassy43** [zheng95z/rgbx#3]
Hi,

Thanks a lot for your amazing work; it's really impressive!

I'm currently trying to reproduce your RGB->X albedo and irradiance numbers on Hypersim and I have two questions:

1. Do you scale-align your albedo prediction to the ground-truth before computing the metrics?
2. How do you handle the varying data range of the ground-truth irradiance when computing PSNR? I have seen that the Hypersim irradiance ground-truth has maximum values that differ greatly for every image. Do you apply any rescaling or clipping?

Thanks a lot for your reply in advance!

**Comment by zheng95z** [comment]
Hi @Guirassy43,

Thanks for your kind words!

> Do you scale-align your albedo prediction to the ground-truth before computing the metrics?

No. We did not post-process the outputs of our models and the baselines.

> How do you handle the varying data range of the ground-truth irradiance when computing PSNR? I have seen that the Hypersim irradiance ground-truth has maximum values that differ greatly for every image. Do you apply any rescaling or clipping?

We use an automaric exposure adjuestment for the high dynamic range inputs. See [here](https://github.com/zheng95z/rgbx/blob/168f2d7c36bc48b91587183cd72fc75c10e5857a/rgb2x/load_image.py#L102-L114).
