### ISSUE TITLE
No Irradiance

### ISSUE THREAD

**Issue by LiZhien712** [zheng95z/rgbx#4]
Hi,

Thanks a lot for your amazing work; it's really impressive!

I'm currently working on removing the original lighting from the reconstructed scene and I have a question:

Can I use the RGB->X to output a no irradiance image, or define a channel like this?

Thanks a lot for your reply in advance!

**Comment by zheng95z** [comment]
Hi @LiZhien712,

Thanks for your kind words!

> Can I use the RGB->X to output a no irradiance image, or define a channel like this?

Are you referring to an image without any shading, or with shading but no shadows?

**Comment by LiZhien712** [comment]
Thank you for your reply! I mean it should be the latter, an image with shading but no shadows, but if we can eliminate diffuse reflections between objects and objects is going to have a better result.

**Comment by zheng95z** [comment]
Then you'll first need that kind of data, which should be easy to be generated using renderers like Blender Cycles. Sadly our models haven't be trained on such data, so they cannot do this.

Best,
