### ISSUE TITLE
Gamma correction in X->RGB

### ISSUE THREAD

**Issue by lefreud** [zheng95z/rgbx#5]
Hi,

I'm wondering if it's the desired behaviour that the X->RGB pipeline applies a gamma-2.2 tonemapping to the images outputted by the model? 

Here is the part of the code I'm referring to:
https://github.com/zheng95z/rgbx/blob/main/x2rgb/pipeline_x2rgb.py#L942-L954
https://github.com/zheng95z/rgbx/blob/main/x2rgb/pipeline_x2rgb.py#L57C9-L57C28

If so, this would mean that the X->RGB model was trained to output *linear* images, but I didn't see anything saying that in the paper, and in the figures, the outputs look tonemapped. Also, I found empically that keeping the gamma correction enabled results in overly bright images, which is not the case when I disable it.

My guess is that this is a bug due to the fact that the other model, RGB->X also uses the same `preprocess` function, but actually needs to gamma 2.2 tonemap the photo fed as input (which is linearized in the gradio demo code). Here's that part of the code (which I think works fine):
https://github.com/zheng95z/rgbx/blob/main/rgb2x/pipeline_rgb2x.py#L690

Let me know what you think :)

**Comment by zheng95z** [comment]
This is a desired behaviour. Both X->RGB and RGB->X models are trained on linear space -- they take linear inputs and produce linear outputs.

**Comment by lefreud** [comment]
Got it! Out of curiosity, is there a specific reason why the training was done in linear space? Better results?

**Comment by zheng95z** [comment]
I guess that's my default mindset when operating on images :).
