### ISSUE TITLE
About hte magicial scaling factor for each AOV

### ISSUE THREAD

**Issue by YMX2022** [zheng95z/rgbx#8]
Hi. Great work.
I have only a small issue about the Magical scaling factors for each AOV, refering to 
https://github.com/zheng95z/rgbx/blob/main/x2rgb/pipeline_x2rgb.py#L788-L794.
I wonder whether this scale is important for the performance (compared with original vae scale) and how to calculate it on the training dataset.

Thanks a lot!

**Comment by zheng95z** [comment]
Hi @YMX2022,

Thanks for your kind words.

Actually, in my test, they made no noticeable difference (training with them vs. without them).

For calculating such values for your dataset, see here: https://github.com/huggingface/diffusers/issues/437.

Best,

**Comment by YMX2022** [comment]
Thanks! It helps a lot.
